<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="InvariantTests.fs" />
    <Compile Include="GenerateTests.fs" />
    <Compile Include="RoundTripProperties.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Etymon.Invariants.FsCheck/Etymon.Invariants.FsCheck.fsproj" />
  </ItemGroup>

</Project>
