<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="IntegrationTests.fs" />
    <Compile Include="MetadataTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <ProjectReference Include="../../src/Etymon.Api.Giraffe/Etymon.Api.Giraffe.fsproj" />
    <ProjectReference Include="../../src/Etymon.Api.AspNetCore/Etymon.Api.AspNetCore.fsproj" />
    <ProjectReference Include="../../src/Etymon.Api.Client/Etymon.Api.Client.fsproj" />
  </ItemGroup>

</Project>
