<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="SchemaTests.fs" />
    <Compile Include="WireFieldTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Etymon.Schema/Etymon.Schema.fsproj" />
  </ItemGroup>

</Project>
