<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="SnapshotTests.fs" />
    <Compile Include="CompatibilityTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Etymon.Schema.Events/Etymon.Schema.Events.fsproj" />
  </ItemGroup>

</Project>
