<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="StrTests.fs" />
    <Compile Include="DictEnvTests.fs" />
    <Compile Include="FilesTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Etymon.Base/Etymon.Base.fsproj" />
  </ItemGroup>

</Project>
